name: Newman CLI Tests Execution

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_api_collection:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      # Set up Node.js (using Node.js version 16.x)
      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      # Install dependencies (including Newman)
      - name: Install dependencies
        run: |
          npm install  # Install dependencies from package.json, including Newman
          npm install -g newman  # Install Newman globally (in case it's not in package.json)

      # Run the Newman Executor script
      - name: Run Newman Executor
        run: |
          node newman_executor.js  # Run the script that will execute the collection and generate reports

      # Check if the Reports folder exists
      - name: Check if Reports folder exists
        run: |
          if [ ! -d "Reports" ]; then echo "Reports folder not found!"; exit 1; fi

      # Upload the HTML Test Report
      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: HTML Test Report
          path: Reports/report-${{ github.run_id }}.html  # Update based on the timestamp in your filename

      # Upload the CSV Results (generated dynamically by newman_executor.js)
      - name: Upload CSV Results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: CSV Results
          path: Reports/failed_API-${{ github.run_id }}.csv  # Ensure this matches the generated CSV file's name
