name: Newman CLI Tests Execution

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  test_api_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Run Newman Executor
        run: node newman_executor.js

      - name: Upload Test Results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Test Results
          path: TestResults
