name: Run Newman Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Newman tests
        run: node newman_executor.js

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: ./Reports/*.html

      - name: Upload CSV report artifact
        uses: actions/upload-artifact@v3
        with:
          name: csv-report
          path: ./Reports/*.csv
